In [0]:
!mkdir dataset
from google.colab import files
src = list(files.upload().values())[0]
open('\dataset','wb').write(src)
!mv sample_mobile_data_1000.csv dataset/
!ls dataset

In [0]:
!curl ifconfig.co

34.76.163.135


In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
!ls /content/gdrive/My\ Drive/
!cp -r /content/gdrive/My\ Drive/BO-* /content/gdrive/My\ Drive/resume
!cd gdrive/My\ Drive/colab

 BO-DA-رزومه‌ها-E0		  nimac.gsite
 colab				  SahabX-Sokan
'Getting started.pdf'		 'اعضای دانشکده.xlsx'
'hadoop meeting feedback.gform'  'پروژه هوش سحاب.gdoc'
'Hadoop Meeting.gslides'	 'مشخصات سرور.gsheet'
 NimaBehrang.pdf


In [0]:
!unzip /content/gdrive/My\ Drive/colab/ml-100k.zip

In [0]:
!ls gdrive/My\ Drive/colab/ml-100k/

allbut.pl  u1.base  u2.test  u4.base  u5.test  ub.base	u.genre  u.occupation
mku.sh	   u1.test  u3.base  u4.test  ua.base  ub.test	u.info	 u.user
README	   u2.base  u3.test  u5.base  ua.test  u.data	u.item


In [11]:
# !cat gdrive/My\ Drive/colab/ml-100k/u.user
import numpy as np
data = np.genfromtxt("/content/gdrive/My Drive/colab/ml-100k/u.data", dtype=int)
# data = np.genfromtxt("/content/gdrive/My Drive/colab/ml-100k/u.data",  dtype=[int,int,int,int])
for num in data:
   num
print(data)



[[      196       242         3 881250949]
 [      186       302         3 891717742]
 [       22       377         1 878887116]
 ...
 [      276      1090         1 874795795]
 [       13       225         2 882399156]
 [       12       203         3 879959583]]


In [0]:
!ls 

In [0]:
!pip install -q tensorflow-gpu==2.0.0a0 matplotlib

     |████████████████████████████████| 332.1MB 74kB/s 
     |████████████████████████████████| 3.0MB 33.9MB/s 
     |████████████████████████████████| 419kB 40.7MB/s 


In [0]:
from tensorflow.python import keras
import tensorflow as tf

In [0]:


input_user = keras.Input(shape=(1,))  # Returns a placeholder tensor
input_item = keras.Input(shape=(1,))  # Returns a placeholder tensor
embed_user = keras.layers.Embedding(2000, 64)(input_user)
embed_item = keras.layers.Embedding(2000, 64)(input_item)
multiply = keras.layers.Multiply()([embed_user, embed_item])
rate = keras.layers.add(tf.unstack(multiply, axis=2))
model = keras.Model(inputs=[input_user, input_item], outputs = keras.activations.sigmoid(rate))
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_17 (InputLayer)           [(None, 1)]          0                                            
__________________________________________________________________________________________________
input_18 (InputLayer)           [(None, 1)]          0                                            
__________________________________________________________________________________________________
embedding_14 (Embedding)        (None, 1, 64)        128000      input_17[0][0]                   
__________________________________________________________________________________________________
embedding_15 (Embedding)        (None, 1, 64)        128000      input_18[0][0]                   
____________________________________________________________________________________________

In [48]:
input_user = keras.Input(shape=(1,))  # Returns a placeholder tensor
input_item = keras.Input(shape=(1,))  # Returns a placeholder tensor
embed_user = keras.layers.Embedding(2000, 64)(input_user)
embed_item = keras.layers.Embedding(2000, 64)(input_item)
dot = keras.layers.dot(inputs=[embed_user, embed_item],axes=2)
model_opt = keras.Model(inputs=[input_user, input_item], outputs = keras.activations.sigmoid(dot))
model_opt.summary()


Model: "model_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_23 (InputLayer)           [(None, 1)]          0                                            
__________________________________________________________________________________________________
input_24 (InputLayer)           [(None, 1)]          0                                            
__________________________________________________________________________________________________
embedding_20 (Embedding)        (None, 1, 64)        128000      input_23[0][0]                   
__________________________________________________________________________________________________
embedding_21 (Embedding)        (None, 1, 64)        128000      input_24[0][0]                   
____________________________________________________________________________________________

In [0]:
fit = model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=10,
                callbacks = [cp_callback, tb_callback], use_multiprocessing=True, batch_size=100,
               validation_split=0.8)

allbut.pl  u1.base  u2.test  u4.base  u5.test  ub.base	u.genre  u.occupation
mku.sh	   u1.test  u3.base  u4.test  ua.base  ub.test	u.info	 u.user
README	   u2.base  u3.test  u5.base  ua.test  u.data	u.item
